80 POKE$9F25,A1
90 POKE$9F2A,89:POKE$9F2B,58

370 COLOR5,0:PRINTCHR$(147)CHR$(14);
380 PRINT"":PRINT" wELCOME FLYBOY,":PRINT""
390 PRINT" i'VE BEEN TOLD YOUR THE BEST PILOT IN THE QUADRANT..."
400 PRINT" lETS HOPE THAT'S TRUE.":PRINT""
410 PRINT" wE HAVE A COLONY ON A SMALL MOON AROUND PLANET vERA c"
420 PRINT"   THAT REQUIRES A DAILY SHIPMENT OF SUPPLIES. ":PRINT""
430 PRINT" fOR THE NEXT 7 DAYS THERE WILL BE A LARGE METEOR"
440 PRINT"   FIELD PASSING BETWEEN US AND THEM. eVRY DAY THE "
450 PRINT"   FIELD WILL GROW FASTER AND MORE DENSE.":PRINT""
460 PRINT" yOU WILL BE PILOTING THE x16 DELIVERY SHUTTLE."
470 PRINT" a SHIP KNOWN FOR IT'S SWIFT MANEUVERABILITY.":PRINT""
480 PRINT" tHE JOB PAYS 100,000 CREDITS FOR THE FIRST DAY."
490 PRINT" 10% WILL BE ADDED EACH DAY. tHERE IS ALSO A TIME"
500 PRINT" BONUS FOR FINISHING EACH MISSION AHEAD OF SHEDULE."
510 PRINT" dON'T GET TO GREEDY, YOU ONLY HAVE ONE LIFE.":PRINT"
520 PRINT" iF YOU SURVIVE YOU'LL BE ABLE TO RETIRE OFF OF 7"
530 PRINT"   DAYS OF WORK.":PRINT""
540 PRINT" gOOD LUCK OUT THERE AND STAY ALERT, i'D HATE TO"
550 PRINT"   LOSE A SHIP."
